/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up a new user */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login a user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the access token; rotates the refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh session and clear the cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password-reset link to every channel on the account
         * @description Always 202, whether or not the address is registered — a different answer would reveal which emails have accounts.
         */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a reset link and set a new password
         * @description Public because the click arrives from a mail or chat client with no session. The token is single-use and revokes any live session.
         */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the password; revokes the refresh session */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List platforms with link status */
        get: operations["SocialPlatformsController_getPlatforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a one-time Telegram deep link for account linking */
        post: operations["SocialPlatformsController_linkTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/email/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a verification email to start receiving reminders there
         * @description The address is only linked once the recipient clicks the link, so an address can never be signed up by someone who does not control it.
         */
        post: operations["SocialPlatformsController_linkEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem the token from a verification email
         * @description Public because the click arrives from a mail client with no session.
         */
        post: operations["SocialPlatformsController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/{platform}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a platform from the account */
        delete: operations["SocialPlatformsController_unlink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks (paginated, filterable) */
        get: operations["TasksController_list"];
        put?: never;
        /** Create a task and schedule its reminders */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by id */
        get: operations["TasksController_getById"];
        put?: never;
        post?: never;
        /** Soft-delete a task and cancel all its jobs */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        /** Update a task; schedule changes restart it */
        patch: operations["TasksController_update"];
        trace?: never;
    };
    "/api/tasks/{taskId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the current reminder */
        post: operations["TasksController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze the current reminder */
        post: operations["TasksController_snooze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/actions/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview the reminder behind an emailed action link
         * @description Read-only on purpose: mail scanners follow links automatically, so nothing here may change task state.
         */
        get: operations["TasksController_previewTokenAction"];
        put?: never;
        /** Perform the action behind an emailed link */
        post: operations["TasksController_performTokenAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The user's effective plan, limits, and usage */
        get: operations["BillingController_getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Purchasable products with prices */
        get: operations["BillingController_getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a Pro purchase; returns the hosted payment page URL
         * @description Also the renewal path: paying while already Pro stacks the new period on top of the remaining one. There is no auto-billing.
         */
        post: operations["BillingController_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/payments/{paymentId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-check a payment against Ziina and settle it
         * @description The return page calls this so payments settle even without a webhook (local dev, or a missed delivery).
         */
        post: operations["BillingController_syncPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/billing/webhooks/ziina": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ziina webhook (HMAC-authenticated)
         * @description Public because Ziina calls it server-to-server; the HMAC signature over the raw body is the authentication. Throttling is skipped so a 429 never burns one of the 3 delivery retries. No @Body() DTO on purpose: the raw bytes are what the signature covers.
         */
        post: operations["BillingController_ziinaWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignUpDto: {
            firstName: string;
            lastName: string;
            email: string;
            /** @description Password (12-72 characters) */
            password: string;
            /** @description E.164 format, e.g. +971501234567 */
            phoneNumber?: string;
        };
        LogInDto: {
            email: string;
            password: string;
        };
        LoginResponseDto: {
            accessToken: string;
        };
        ForgotPasswordDto: {
            /** @description Address the account was registered with */
            email: string;
        };
        ResetPasswordDto: {
            /** @description Single-use token from the reset link */
            token: string;
            /** @description New password (12-72 characters) */
            newPassword: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            /** @description New password (12-72 characters) */
            newPassword: string;
        };
        UserResponseDto: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phoneNumber?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateUserDto: {
            firstName?: string;
            lastName?: string;
            /** @description E.164 format, e.g. +971501234567 */
            phoneNumber?: string;
        };
        LinkedPlatformStatusDto: {
            /** @enum {string} */
            platform: "telegram" | "whatsapp" | "email" | "sms";
            /** @description Whether Remindo has an adapter for it yet */
            implemented: boolean;
            /** @description Whether the user's current plan may deliver here */
            availableOnPlan: boolean;
            /**
             * @description The plan that unlocks this platform, when locked
             * @enum {string}
             */
            requiredPlan?: "free" | "pro";
            linked: boolean;
            /** Format: date-time */
            linkedAt?: string;
        };
        LinkPlatformResponseDto: {
            /**
             * @description One-time deep link the user opens to link their account
             * @example https://t.me/RemindoBot?start=<nonce>
             */
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        LinkEmailDto: {
            /** @description Address to send reminders to */
            email: string;
        };
        LinkEmailResponseDto: {
            /** @description Whether the verification email went out */
            sent: boolean;
            email: string;
            /** Format: date-time */
            expiresAt: string;
        };
        VerifyEmailDto: {
            /** @description Single-use token from the verification email */
            token: string;
        };
        VerifyEmailResponseDto: {
            /** @enum {string} */
            outcome: "LINKED" | "ALREADY_LINKED" | "REPLACED_PREVIOUS";
            email: string;
        };
        CreateTaskDto: {
            title: string;
            content: string;
            /** @enum {string} */
            priority: "normal" | "important" | "urgent";
            platforms: ("telegram" | "whatsapp" | "email" | "sms")[];
            /**
             * Format: date-time
             * @description Must be in the future (UTC)
             */
            dueDate: string;
            /** @enum {string} */
            recurrence: "once" | "daily" | "weekly" | "days_of_week" | "monthly" | "quarterly" | "yearly";
            /**
             * @description UTC weekdays, 0 = Sunday … 6 = Saturday. Required when recurrence is days_of_week; ignored (and stored empty) for every other recurrence.
             * @example [
             *       1,
             *       2
             *     ]
             */
            recurrenceDays?: number[];
        };
        TaskResponseDto: {
            id: string;
            title: string;
            content: string;
            /** @enum {string} */
            status: "scheduled" | "reminding" | "snoozed" | "acknowledged" | "missed";
            /** @enum {string} */
            priority: "normal" | "important" | "urgent";
            platforms: ("telegram" | "whatsapp" | "email" | "sms")[];
            /** @enum {string} */
            recurrence: "once" | "daily" | "weekly" | "days_of_week" | "monthly" | "quarterly" | "yearly";
            /** @description UTC weekdays (0 = Sunday) for days_of_week tasks; empty otherwise */
            recurrenceDays: number[];
            /** Format: date-time */
            dueDate: string;
            occurrenceSeq: number;
            occurrenceFiredAt?: Record<string, never> | null;
            attempt: number;
            snoozeCount: number;
            acknowledgedAt?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @description True when the user's plan currently suppresses delivery for this task */
            deliverySuppressed?: boolean;
        };
        PageMetaDto: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
        TaskListResponseDto: {
            items: components["schemas"]["TaskResponseDto"][];
            meta: components["schemas"]["PageMetaDto"];
        };
        UpdateTaskDto: {
            title?: string;
            content?: string;
            /** @enum {string} */
            priority?: "normal" | "important" | "urgent";
            platforms?: ("telegram" | "whatsapp" | "email" | "sms")[];
            /**
             * Format: date-time
             * @description Must be in the future (UTC)
             */
            dueDate?: string;
            /** @enum {string} */
            recurrence?: "once" | "daily" | "weekly" | "days_of_week" | "monthly" | "quarterly" | "yearly";
            /**
             * @description UTC weekdays, 0 = Sunday … 6 = Saturday. Required when recurrence is days_of_week; ignored (and stored empty) for every other recurrence.
             * @example [
             *       1,
             *       2
             *     ]
             */
            recurrenceDays?: number[];
        };
        TaskActionResponseDto: {
            /** @enum {string} */
            outcome: "acknowledged" | "snoozed";
        };
        TaskActionPreviewDto: {
            /** @enum {string} */
            action: "confirm" | "snooze";
            title: string;
            content: string;
            /** @enum {string} */
            status: "scheduled" | "reminding" | "snoozed" | "acknowledged" | "missed";
            /** @enum {string} */
            priority: "normal" | "important" | "urgent";
            /** Format: date-time */
            dueDate: string;
            /** @description False when the reminder has already been handled or moved on */
            actionable: boolean;
            reason?: string;
        };
        PlanLimitsDto: {
            /** @description null = unlimited */
            maxActiveTasks: number | null;
            platforms: ("telegram" | "whatsapp" | "email" | "sms")[];
        };
        SubscriptionUsageDto: {
            activeTasks: number;
        };
        SubscriptionResponseDto: {
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            periodEnd: string | null;
            /** @enum {string|null} */
            product: "pro_monthly" | "pro_yearly" | null;
            limits: components["schemas"]["PlanLimitsDto"];
            usage: components["schemas"]["SubscriptionUsageDto"];
        };
        ProductDto: {
            /** @enum {string} */
            product: "pro_monthly" | "pro_yearly";
            /** @description Price in fils (AED minor units) */
            amountFils: number;
            currency: string;
            periodDays: number;
        };
        CheckoutDto: {
            /** @enum {string} */
            product: "pro_monthly" | "pro_yearly";
        };
        CheckoutResponseDto: {
            paymentId: string;
            /** @description Ziina's hosted payment page */
            redirectUrl: string;
        };
        PaymentSyncResponseDto: {
            paymentId: string;
            /** @enum {string} */
            status: "pending" | "completed" | "failed" | "canceled";
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            periodEnd: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    SocialPlatformsController_getPlatforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedPlatformStatusDto"][];
                };
            };
        };
    };
    SocialPlatformsController_linkTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkPlatformResponseDto"];
                };
            };
        };
    };
    SocialPlatformsController_linkEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkEmailDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkEmailResponseDto"];
                };
            };
        };
    };
    SocialPlatformsController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResponseDto"];
                };
            };
        };
    };
    SocialPlatformsController_unlink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Case-insensitive substring match against the task title or content. */
                q?: string;
                status?: "scheduled" | "reminding" | "snoozed" | "acknowledged" | "missed";
                priority?: "normal" | "important" | "urgent";
                sortBy?: "dueDate" | "priority" | "createdAt";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponseDto"];
                };
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponseDto"];
                };
            };
        };
    };
    TasksController_snooze: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponseDto"];
                };
            };
        };
    };
    TasksController_previewTokenAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionPreviewDto"];
                };
            };
        };
    };
    TasksController_performTokenAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActionResponseDto"];
                };
            };
        };
    };
    BillingController_getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponseDto"];
                };
            };
        };
    };
    BillingController_getProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
        };
    };
    BillingController_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponseDto"];
                };
            };
        };
    };
    BillingController_syncPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSyncResponseDto"];
                };
            };
        };
    };
    BillingController_ziinaWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-hmac-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
